ler.s: src/serverhandler.cxx.s
.PHONY : src/serverhandler.s

# target to generate assembly for a file
src/serverhandler.cxx.s:
	$(MAKE) -f CMakeFiles/ep2-server.dir/build.make CMakeFiles/ep2-server.dir/src/serverhandler.cxx.s
.PHONY : src/serverhandler.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... ep2-client"
	@echo "... ep2-server"
	@echo "... rebuild_cache"
	@echo "... src/TCPconnection.o"
	@echo "... src/TCPconnection.i"
	@echo "... src/TCPconnection.s"
	@echo "... src/client.o"
	@echo "... src/client.i"
	@echo "... src/client.s"
	@echo "... src/command.o"
	@echo "... src/command.i"
	@echo "... src/command.s"
	@echo "... src/eventmanager.o"
	@echo "... src/eventmanager.i"
	@echo "... src/eventmanager.s"
	@echo "... src/prompt.o"
	@echo "... src/prompt.i"
	@echo "... src/prompt.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
	@echo "... src/serverdata.o"
	@echo "... src/serverdata.i"
	@echo "... src/serverdata.s"
	@echo "... src/serverhandler.o"
	@echo "... src/serverhandler.i"
	@echo "... src/serverhandler.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system


